import = [ "~/.config/alacritty/alacritty-theme/themes/tokyo-night.toml" ]
[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 8
decorations = "Buttonless"
opacity = 0.80
blur = true

[font]
normal.family = "FiraCode Nerd Font"
size = 16

